const dummyStudentExample = {
  total: 20,
  checked: 16,
  not_checked: 4,
  student_list: [
    { id: 1, name: '고태완', self_check: true },
    { id: 2, name: '고태완', self_check: true },
    { id: 3, name: '고태완', self_check: false },
    { id: 4, name: '고태완', self_check: true },
    { id: 5, name: '고태완', self_check: true },
    { id: 6, name: '고태완', self_check: true },
    { id: 7, name: '고태완', self_check: false },
    { id: 8, name: '고태완', self_check: true },
    { id: 9, name: '고태완', self_check: false },
    { id: 10, name: '고태완', self_check: true },
    { id: 11, name: '고태완', self_check: true },
    { id: 12, name: '고태완', self_check: true },
    { id: 13, name: '고태완', self_check: true },
    { id: 14, name: '고태완', self_check: false },
    { id: 15, name: '고태완', self_check: true },
    { id: 16, name: '고태완', self_check: true },
    { id: 17, name: '고태완', self_check: true },
    { id: 18, name: '고태완', self_check: true },
    { id: 19, name: '고태완', self_check: true },
    { id: 20, name: '고태완', self_check: true },
  ],
};
export default dummyStudentExample;
