export const offices = [
  '강원',
  '경기',
  '경남',
  '경북',
  '광주',
  '대구',
  '대전',
  '부산',
  '서울',
  '세종',
  '울산',
  '인천',
  '전남',
  '전북',
  '제주',
  '충남',
  '충북',
];

export const hcheckMatchURL = {
  강원: 'https://eduro.kwe.go.kr/',
  경기: 'https://eduro.goe.go.kr/',
  경남: 'https://eduro.gne.go.kr/',
  경북: 'https://eduro.gbe.kr/',
  광주: 'https://eduro.gen.go.kr/',
  대구: 'https://eduro.dge.go.kr/',
  대전: 'https://eduro.use.go.kr/',
  부산: 'https://eduro.pen.go.kr/',
  서울: 'https://eduro.sen.go.kr/',
  세종: 'https://eduro.sje.go.kr/',
  울산: 'https://eduro.use.go.kr/',
  인천: 'https://eduro.ice.go.kr/',
  전남: 'https://eduro.jne.go.kr/',
  전북: 'https://eduro.jbe.go.kr/',
  제주: 'https://eduro.jje.go.kr/',
  충남: 'https://eduro.cne.go.kr/',
  충북: 'https://eduro.cbe.go.kr/',
};
