export const offices = [
  '강원',
  '경기',
  '경남',
  '경북',
  '광주',
  '대구',
  '대전',
  '부산',
  '서울',
  '세종',
  '울산',
  '인천',
  '전남',
  '전북',
  '제주',
  '충남',
  '충북',
];

export const hcheckMatchURL = {
  강원: 'https://eduro.kwe.go.kr/',
  경기: 'https://eduro.goe.go.kr/',
  경남: 'https://eduro.gne.go.kr/',
  경북: 'https://eduro.gbe.kr/',
  광주: 'https://eduro.gen.go.kr/',
  대구: 'https://eduro.dge.go.kr/',
  대전: 'https://eduro.use.go.kr/',
  부산: 'https://eduro.pen.go.kr/',
  서울: 'https://eduro.sen.go.kr/',
  세종: 'https://eduro.sje.go.kr/',
  울산: 'https://eduro.use.go.kr/',
  인천: 'https://eduro.ice.go.kr/',
  전남: 'https://eduro.jne.go.kr/',
  전북: 'https://eduro.jbe.go.kr/',
  제주: 'https://eduro.jje.go.kr/',
  충남: 'https://eduro.cne.go.kr/',
  충북: 'https://eduro.cbe.go.kr/',
};

export const matchInitialEachOffices = {
  강원: 'kwe',
  경기: 'goe',
  경남: 'gne',
  경북: 'gbe',
  광주: 'gen',
  대구: 'dge',
  대전: 'dje',
  부산: 'pen',
  서울: 'sen',
  세종: 'sje',
  울산: 'use',
  인천: 'ice',
  전남: 'jne',
  전북: 'jbe',
  제주: 'jje',
  충남: 'cne',
  충북: 'cbe',
};

export const reverseMatchInitialEachOffices = {
  kwe: '강원도교육청',
  goe: '경기도교육청',
  gne: '경상남도교육청',
  gbe: '경상북도교육청',
  gen: '광주광역시교육청',
  dge: '대구광역시교육청',
  dje: '대전광역시교육청',
  pen: '부산광역시교육청',
  sen: '서울특별시교육청',
  sje: '세종특별자치시교육청',
  use: '울산광역시교육청',
  ice: '인천광역시교육청',
  jne: '전라남도교육청',
  jbe: '전라북도교육청',
  jje: '제주특별자치도교육청',
  cne: '충청남도교육청',
  cbe: '충청북도교육청',
};
